# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_CLIENT, ROLE_MECHANIC
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/login$
            security: false

        admin_login:
            pattern: ^/admin/login$
            security: false

        admin:
            pattern: ^/admin
            form_login:
                provider: fos_userbundle
                login_path: admin_login
                check_path: admin_login_check
                default_target_path: admin_dashboard
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: admin_logout
                target: admin_login
            anonymous: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: homepage
                success_handler: app.security.authentication_handler
                failure_handler: app.security.authentication_handler
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: fos_user_security_logout
                target: homepage
            anonymous: true


    access_control:

        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }